service: customer

provider:
  name: aws
  runtime: nodejs6.10
  profile: shoutak
  stage: dev
  region: ap-northeast-1

plugins:
  - serverless-offline
  - serverless-webpack

functions:
  users:
    handler: handlers.users
    events:
      - http:
          path: users
          method: get
      - http:
          path: users/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
      - http:
          path: users
          method: post
      - http:
          path: users/{id}
          method: put
          request:
            parameters:
              paths:
                id: true

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
