service: customer

provider:
  name: aws
  runtime: nodejs6.10
  profile: shoutak
  stage: dev
  region: ap-northeast-1

plugins:
  - serverless-webpack

functions:
  createUser:
    handler: handlers.createUser
    events:
      - http:
          path: users/create
          method: get

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1